name = "A Ducky Server"
motd = "This lobby is powered by Ducky.\nType !help to see commands."
game_version = "1.11"
lobby_code = "DUCKYY"
max_players = 25
unlisted = false
tag_talkative = false
tag_quiet = false
tag_grinding = false
tag_chill = false
tag_silly = false
tag_hardcore = false
tag_mature = false
tag_modded = true
ban_list = []
