name = "A Ducky Server"
motd = "This lobby is powered by Ducky.\nType !help to see commands."
game_version = "1.1"
lobby_code = "DUCKYY"
max_players = 25
code_only = true
adult_only = false
ban_list = []
